 Vagrant.configure("2") do |config|
 	config.vm.box = "bento/ubuntu-20.04"
	
	#config.vm.network "forwarded_port", guest: 9200, host: 9200
	#config.vm.network "forwarded_port", guest: 9100, host: 9100
	#config.vm.network "forwarded_port", guest: 19999, host: 19999
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
		v.name = "devops20-vm01"
	end
 end