---
clickhouse:
  hosts:
    dv20-clickhouse:
      ansible_host: 158.160.38.117
      ansible_user: centos

vector:
  hosts:
    dv20-vector:
      ansible_host: 158.160.48.88
      ansible_user: centos

lighthouse:
  hosts:
    dv20-lighthouse:
      ansible_host: 158.160.44.242
      ansible_user: centos
