---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 192.168.56.4
    jenkins-agent-01:
      ansible_host: 192.168.56.5
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant